name: Testing
on: push
jobs:
  test-and-build:
    name: Test and Build
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12, 14, 16]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Using node v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install packages
        run: npm install

      - name: Tests
        run: npm run test:full

      - name: Build
        run: npm run build

      - name: Publish code coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./**/**/coverage-final.json
          flags: unittests
          name: universal
          fail_ci_if_error: true
          verbose: true
